version: '3.5'
services: 
  # back:
  #   environment:
  #     - FLASK_ENV=development
  #   image: docker-flask
  #   container_name: back_flask
  #   ports: 
  #     - 5000:5000
  #     - 5050:5050
  #   volumes:
  #     - ./server:/app
  #   depends_on:
  #     [db]
  # front:
  #   image: react-app
  #   container_name: front_react
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     [back,
  #     db]
  #   volumes:
  #     - ./client:/app
  todo_service:
    environment:
      - FLASK_ENV=production
    image: docker-flask
    container_name: todo_service
    ports:
      - 5002:5002
    volumes:
      - ./server/services/todo:/app
    depends_on:
      [db]
  user_service:
    environment:
      - FLASK_ENV=production
    image: docker-flask
    container_name: user_service
    ports:
      - 5001:5001
    volumes:
      - ./server/services/users:/app
    depends_on:
      [db]
  db:
    image: postgres
    container_name: db
    volumes:
      - ./config:/docker-entrypoint-initdb.d
    environment: 
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432
  gateway:
    image: nrel/api-umbrella
    container_name: gateway
    volumes:
      - ./config:/etc/api-umbrella
    ports:
      - 80:80
      - 443:443

